### ISSUE TITLE
Movecraft-Repair integration

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft-WorldGuard#11]
Sparked on by the discussion in https://github.com/APDevTeam/Movecraft-Repair/issues/29, we should create a new region flag which allows configuration of repairs in worldguard regions.  The default behavior would follow that of the `build` flag, denying a repair in a region which you are not a member or owner of.

**Comment by goodroach** [comment]
To be clear, should this event check happen before the repair state starts? Though honestly, I think having its own flag that's not reliant on the build tag would be fine. This is because we're checking thousands of blocks here, and I don't think running thousands of build events simultaneously is very performant. Just making sure the hitbox doesn't intersect will save you a lot of time I think.

**Comment by TylerS1066** [comment]
> should this event check happen before the repair state starts?

I would tie this into the mentioned [`ProtoRepairCreateEvent`](https://github.com/APDevTeam/Movecraft-Repair/blob/main/src/main/java/net/countercraft/movecraft/repair/events/ProtoRepairCreateEvent.java) which is fired on the first click of a repair sign.


> I think having its own flag that's not reliant on the build tag would be fine.

My expectation was to have it's own flag but fall back to the build flag if it is undefined, [similar to movement](https://github.com/APDevTeam/Movecraft-WorldGuard/blob/main/src/main/java/net/countercraft/movecraft/worldguard/listener/CraftTranslateListener.java).


> checking thousands of blocks here

Movecraft-WorldGuard has a [neat little optimization trick](https://github.com/APDevTeam/Movecraft-WorldGuard/blob/main/src/main/java/net/countercraft/movecraft/worldguard/utils/WorldGuardUtils.java#L63) which drastically cuts down the checks, in addition, WorldGuard is highly optimized for fast flag checks.

**Comment by TomLewis** [comment]
Only just noticed this was tagged in my old ticket, any luck with the implementation? Would it work with griefprevention too if it's checking for if you have build permissions

**Comment by TylerS1066** [comment]
> Would it work with griefprevention too if it's checking for if you have build permissions

This repo is for a WorldGuard integration, and will not work with other protection plugins.  You'd have to find a separate addon for GriefProtection.
