### ISSUE TITLE
No release for 1.17

### ISSUE THREAD

**Issue by JustinDevB** [APDevTeam/Movecraft-WorldGuard#5]
The repository was updated to 1.17, but there is no release build.

I was going to build my own, but pom.xml has a lot of system dependencies...

**Comment by TylerS1066** [comment]
This plugin should have no incompatibilities with 1.17 (or 1.17.1).  The update to the repo was to support building the latest Movecraft 8 versions which do support 1.17.


Open a new issue with any problems with running the latest release on 1.17.



As to building the plugin, you can grab the latest dev builds from the [GitHub Actions tab](https://github.com/APDevTeam/Movecraft-WorldGuard/actions) a few minutes after each commit goes live (click on the build, download the Movecraft-WorldGuard_Dev-Build zipfile and inside will be a development jar).

If you want to work on developing it locally, you will need to first setup your Movecraft development environment (see the Movecraft readme), then Movecraft-Combat dev environment (see the respective readme) and then you need to clone Movecraft-WorldGuard and set it up in the same folder (so Movecraft, Movecraft-Combat and Movecraft-WorldGuard's folders are next to each other).

**Comment by JustinDevB** [comment]
Definitely has incompatibilies

https://pastebin.com/xC58P3ih

Get a similar error for every addon plugin

**Comment by TylerS1066** [comment]
Ah my apologies, you will need to download the latest pre-releases for support of 1.14+.

For example, you will need [Movecraft-WorldGuard 1.a.0](https://github.com/APDevTeam/Movecraft-WorldGuard/releases/tag/1.a.0).
